Completed Task 07 (it was horrible)
ivmulin/TPP pull request #7
Opened 2023-12-09 19:17 UTC by ivmulin

Эта чудесная система выбраковывала каждое моё решение, не говоря, в чём ошибка (пункты C и G пробовал решить буквально раз пятьдесят). Я не понимаю, что от меня хотят. Здоровье важнее...

2023-12-11 20:18 UTC, IlyaRyzhov commented
Да, конечно, здоровье в первую очередь :)
Система принятия решений действительно не очень понятно пишет про ошибки, приложи, пожалуйста, скрины заданий, которые не приняла система

2023-12-11 20:27 UTC, IlyaRyzhov requested changes
Да, конечно, здоровье в первую очередь :)
Система принятия решений действительно не очень понятно пишет про ошибки, приложи, пожалуйста, скрины заданий, которые не приняла система

2023-12-14 06:24 UTC, ivmulin commented
Собрался с силами и дорешал.
( В пункте C предполагается, что мы знакомы с методами `__str__` и `__repr__` и тем, как их переписывать )

2023-12-15 17:00 UTC, IlyaRyzhov approved these changes

2023-12-17 16:44 UTC, ivmulin commented
Честно говоря, с последними номерами без помощи не справился бы

2023-12-29 10:06 UTC, merged